prefix iisg: <https://iisg.amsterdam/vocab/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
select ?place (count(?address) as ?n) {
  ?address iisg:place/rdfs:label ?place.
}
group by ?place
order by desc(?n)
