prefix def: <http://na.metamatter.nl/NadereToegangen/ontology>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
select (sum(?length)/1000 as ?sum) {
  ?film def:mediumLength ?string.
  bind(xsd:float(replace(?string," meter$","")) as ?length)
}
