prefix dct: <http://purl.org/dc/terms/>
prefix foaf: <http://xmlns.com/foaf/0.1/>
prefix geo: <http://www.opengis.net/ont/geosparql#>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix rce: <https://triply.cc/rce/def/>
prefix vcard: <http://www.w3.org/2006/vcard/ns#>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
select distinct ?created ?widget {
  bind("11"^^xsd:string as ?huisnummer)
  bind("9405VJ"^^xsd:string as ?postcode)
  ?monument rce:huisnummer ?huisnummer;
            vcard:postal-code ?postcode.
  ?image dct:created ?created;
         foaf:depicts ?monument;
         rce:locator ?url.
  bind(concat('<figure><img src="',?url,'"><figcaption>',?created,'</figcaption></figure>') as ?widget)
}
order by ?created
