prefix energielabels: <https://data.labs.pdok.nl/def/energielabels/>
prefix graph: <https://data.labs.pdok.nl/graph/>
select
  ?energielabel
  ?ep
  ?huisnummer
  ?huisnummertoevoeging
  ?opnamedatum
  ?postcode
  ?registratiedatum
{
  bind("11"^^xsd:string as ?huisnummer)
  bind("9405VJ"^^xsd:string as ?postcode)
  graph graph:energielabels {
    ?record energielabels:e_label ?energielabel;
            energielabels:ep ?ep;
            energielabels:opname_datum ?opnamedatum;
            energielabels:pand_huisnummer ?huisnummer;
            energielabels:pand_postcode ?postcode;
            energielabels:registratie_datum ?registratiedatum
    optional { ?record energielabels:pand_huisnummer_toev ?huisnummertoevoeging. }
  }
}
limit 5
