prefix buurt: <https://data.labs.pdok.nl/cbs/id/buurt/>
prefix cbs: <https://data.labs.pdok.nl/cbs/def/>
select
  ?basisschool
  ?brandweer
  ?huisarts
  ?kinderdagverblijf
  ?supermarkt
{
  graph <https://data.labs.pdok.nl/graph/wijkbuurt-2015> {
    buurt:BU01069911
      cbs:basisschoolAfstand ?basisschool;
      cbs:brandweer ?brandweer;
      cbs:huisartsenpraktijkAfstand ?huisarts;
      cbs:kinderdagverblijfAfstand ?kinderdagverblijf;
      cbs:supermarktAfstand ?supermarkt.
  }
}
order by ?p
