prefix foaf: <http://xmlns.com/foaf/0.1/>
prefix geo: <http://www.opengis.net/ont/geosparql#>
prefix iisg: <https://iisg.amsterdam/vocab/>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix schema: <http://schema.org/>
select ?plaats (sample(?vorm) as ?vorm) (sample(?vormLabel) as ?vormLabel) {
  ?spel a schema:Game ;
    foaf:depiction/foaf:thumbnail ?url ;
    schema:about ?plaats ;
    schema:name ?spelNaam
  filter not exists { ?url iisg:access "closed"@en }
  ?plaats a schema:Place ;
    schema:name ?plaatsLabel ;
    owl:sameAs/((iisg:hasTemporalSlice/geo:hasGeometry/geo:asWKT)|(geo:hasGeometry/geo:asWKT)) ?vorm
  bind(concat('<h4>',str(?spelNaam),' is a game from ',str(?plaatsLabel),'</h4><img src="',str(?url),'" width="300">') as ?vormLabel)
}
group by ?plaats
