prefix dct: <http://purl.org/dc/terms/>
prefix person: <https://pureacc.knaw.nl/ws/api/510/persons/>
prefix schema: <http://schema.org/>
select ?title {
  person:e250d487-0607-4604-81ca-9a285162ee5c schema:contributor/dct:title ?title .
}
