prefix iisg: <https://iisg.amsterdam/vocab/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
select ?topic ?label (count(?item) as ?n) {
  ?item iisg:topic ?topic
  optional {
    ?topic rdfs:label ?label
  }
}
group by ?topic ?label
order by desc(?n)
limit 10
