prefix graph: <https://iisg.amsterdam/graph/>
prefix loc: <http://id.loc.gov/vocabulary/relators/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix schema: <http://schema.org/>
select ?person
       ?name
       (count(distinct ?role) as ?n)
       (group_concat(distinct ?label;separator=' ') as ?label)
{
  graph graph:collection {
    ?item ?role ?person .
    ?person schema:name ?name .
  }
  ?role rdfs:subPropertyOf* loc:role ;
        rdfs:label ?label .
}
group by ?person ?name
order by desc(?n)
limit 10
