prefix ll: <https://lodlaundromat.org/def/>
select
  ?code
  ?message
  (replace(?errors,'[0-9](?=(?:[0-9]{3})+(?![0-9]))','$0.') as ?errors)
{
  {
    select ?code ?message (count(?error) as ?errors) {
      ?error a ll:ArchiveError;
        ll:code ?code;
        ll:message ?message.
    }
    group by ?code ?message
    order by desc(?errors)
  }
}
