prefix ll: <https://lodlaundromat.org/def/>
select
  ?document
  (replace(?statements,'[0-9](?=(?:[0-9]{3})+(?![0-9]))','$0.') as ?statements)
{
  {
    select ?document ?statements {
      ?document
        ll:quadruples ?quadruples;
        ll:triples ?triples.
      bind(?quadruples + ?triples as ?statements)
    }
    order by desc(?statements)
    limit 10
  }
}
