prefix ll: <https://lodlaundromat.org/def/>
select
  ?c
  (replace(?errors,'[0-9](?=(?:[0-9]{3})+(?![0-9]))','$0.') as ?errors)
{
  {
    select ?c (count(?error) as ?errors) {
      ?document ll:error ?error.
      ?error a ?c.
    }
    group by ?c
    order by desc(?errors)
  }
}
