prefix ll: <https://lodlaundromat.org/def/>
select
  ?status
  (replace(?documents,'[0-9](?=(?:[0-9]{3})+(?![0-9]))','$0.') as ?documents)
{
  {
    select ?status (count(?document) as ?documents) {
      ?document a ll:HttpReply ;
        ll:status ?status.
    }
    group by ?status
    order by desc(?documents)
  }
}
