prefix ll: <https://lodlaundromat.org/def/>
select
  (replace(?triples,'[0-9](?=(?:[0-9]{3})+(?![0-9]))','$0.') as ?triples)
  (replace(?quadruples,'[0-9](?=(?:[0-9]{3})+(?![0-9]))','$0.') as ?quadruples)
  (replace(?statements,'[0-9](?=(?:[0-9]{3})+(?![0-9]))','$0.') as ?statements)
{
  {
    select (sum(?triples) as ?triples) {
      _:1 ll:triples ?triples.
    }
  }
  {
    select (sum(?quadruples) as ?quadruples) {
      _:1 ll:quadruples ?quadruples.
    }
  }
  bind(?triples + ?quadruples as ?statements)
}
