prefix energielabels: <https://data.labs.pdok.nl/def/energielabels/>
prefix graph: <https://data.labs.pdok.nl/graph/>
select ?s {
  ?s energielabels:pand_postcode ?postcode.
  # Assen postcode: 9400-9408
  filter(strstarts(?postcode,"9400") ||
         strstarts(?postcode,"9401") ||
         strstarts(?postcode,"9402") ||
         strstarts(?postcode,"9403") ||
         strstarts(?postcode,"9404") ||
         strstarts(?postcode,"9405") ||
         strstarts(?postcode,"9406") ||
         strstarts(?postcode,"9407") ||
         strstarts(?postcode,"9408"))
}
limit 100
