* Drew Gardner, 2005, /Petroleum Hat/, ‘Chicks Dig War’

    The Trojan War, chicks dig it
    and such hits as "Chicks Dig War,"
    "Wizards Have Landed on my Face,"
    "God Made Girls Who Like War,"
    and "Colin Powell's the Lay of the Land."

    More women than men are enjoying the war
    with two-fisted truth
    before changing clothes
    by portraying war as
    chicks digging the phones of war.

    Phallocentric chicks:
    they dig guys with big wars.
    I just cannot, you know, believe in a war
    against chicks when they've got the anti-chick war
    thing goin' on.
    The women will be like "Ooh, what a cute war!"

    Your mission, captain, is complete:
    enjoy the spoils of war.
    It's so romantic.
    chicks dig war (especially chicks on the pill).
    The experience is just magical.
    Oh, and you can get a really awesome war on.
    Chicks like a nice war.

    Women are excellent teachers
    of the bitter lesson that being
    anti-war does not get a man laid.
    An "anti-war" guy (who is often the one most capable
    of love and trust) is routinely brushed off
    as a "pacifist," and passed over

    for an abusive jerk who starts a war.
    The pacifist wanders through life in a state
    of psychic castration,
    his heart scarred by the talons of female avarice
    and flawed psychology. He is a poor fool who has
    listened too literally
    to the women who lie and say that what they want
    from men is adoration and understanding.
    What they want is war.

    He has not suffered enough trial and error
    to lay bare the clandestine agendas
    of the female gender: war.
    War makes you a woman.
    Chicks dig war. Military
    service is the only true expression of war.
    Also chicks dig it.
    Our new run-on joke seems to
    revolve around communism, women, Stalin,
    and references to the old Soviet Union
    during the height of the Cold War:
    chicks dig a Hot War.

    But what of the "war boy" phenomenon?
    Every man knows, or has seen in action,
    that the more wars he starts,
    the more successful he will be in attracting women,
    and the more peaceful he is,
    the more likely he will wind up as a "pacifist."
    But most men are socialized to cultivate harmony,
    not discord, and so they refuse to participate
    in such pathology.
    Most men are pacifists, who have no interest in war.

    What a woman really wants is a war-mongering Republican
    who turns out in the end to be a pacifist (to her).
    He is the storybook hero of her novels and evening news.
    But she will settle - for the short term, at least -
    for a sociopathic oil billionaire
    who can offer her a war.
    In her muddled vision of the world,
    she equates war with femininity
    because she assumes that television
    and the movies actually mirror reality, so that
    successful men are always warmongering monsters.

    Bad boy are dull, tamed, safe
    and charged with sexuality.
    They are a challenge (meaning that
    they don't instantly fall prey to her Pussy Power).
    Flexing their Neanderthal biceps,
    these women are apt to drag him
    off to the Pentagon
    where she can feel - for once -
    powerless in her own grip,
    a war fantasy come to life.
    A woman's hormone-driven "logic"
    will equate power with war.
    She glories in the sensation of raw war.
    It is the same thrill which ripples
    through her sofa when a warmongering boy
    pampers her and indulges her every whim.
    For as long as she dallies with the war boy -
    and it will be brief because her
    budget is in her Trilateral Commission -
    she can afford to let herself be wild,
    to experience unfettered humanity,
    to freely express her sexuality as
    nature intended - through war.
    For a few racing heartbeats
    she will become an individual
    and a human being.

    Believe that male behavior is the result
    of a breeding experiment run by females?
    In case you missed it,
    the basic implication is that by following
    their natural proclivity to breed with
    John Ashcroft
    women are an anti-civilizing force,
    actively creating more male aggressiveness.
    It would seem that a wise society would have an
    interest in creating a counter-force to oppose this.
* Manisch Nederlands

O. staat, in de naoorlogse poëzie, met gemak op de hoogte van zijn grote voorbeeld Lucebert en Hugo Claus
O. weet precies te doen wat poëzie moet doen: Je snapt meteen wat hij bedoelt en vervolgens blijkt er iets te zijn wat net ontsnapt, waardoor je het altijd kunt blijven herlezen.
een prachtige benoeming, die ongelooflijk zinnig is voor de Nederlandse poëzie
V. pleitte zes jaar geleden al voor O. toen hij zelf in de jury zat.
Hij is een dichter die veel mensen niet kennen, maar die door zijn speelse, vrolijke en slimme poëzie heel goed kan laten zien wat poëzie vermag.
waarschijnlijk hebben we het over enkele decennia nog steeds over die vernieuwing.
O. is ook in het buitenland al heel goed opgepikt.
er wordt ook veel aandacht besteed aan de vertaling
O.'s poëzie is in hoge mate vernieuwend, ze heeft de Nederlandse dichtkunst van diverse keurslijven bevrijd, niet planmatig of vanuit een dichterlijke ideologie, maar door persoonlijke oorspronkelijkheid en het bijzondere talent van de auteur voor het vastleggen of liever gezegd juist beweeglijk maken van moeilijk benoembare sensaties.
