prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix owl: <http://www.w3.org/2002/07/owl#>
select ?c ?label (count(?i) as ?n) {
  ?c owl:sameAs*/rdfs:subClassOf/owl:sameAs* <http://www.wikidata.org/entity/Q65943> .
  optional {
    ?c rdfs:label ?label .
    filter(lang(?label) = "en")
    ?i a ?c .
  }
}
group by ?c ?label
order by desc(?n)
