prefix brt: <http://brt.basisregistraties.overheid.nl/def/top10nl#>
prefix geo: <http://www.opengis.net/ont/geosparql#>
select ?building ?shape {
  ?building a brt:Zwembad_gebouw ;
    geo:hasGeometry/geo:asWKT ?shape .
}
